- name: Configure EC2 Instances
  hosts: tag_Environment_production
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started

